### PR TITLE
Update19

### PR DESCRIPTION
**Pull request by BILLYBELT**

### CODE REVIEW

**Comment by BILLYBELT** [comment]
Hi ! Why you don't uplod lines 2800 to 3000 ?

Le mar. 23 juin 2020 à 12:30, Chris Fenwick <notifications@github.com> a
écrit :

**Comment by lexipenia** [comment]
> Hi ! Why you don't uplod lines 2800 to 3000 ?

@BILLYBELT Sorry, I'm not sure what you're referring to. I'm just merging in your translations.

Did you mean to @Marcpepe ?

**Comment by BILLYBELT** [comment]
I did the translation of lines 2800 to 3000 and it is not translated

Le mar. 23 juin 2020 à 12:50, Chris Fenwick <notifications@github.com> a
écrit :

**Comment by lexipenia** [comment]
> I did the translation of lines 2800 to 3000 and it is not translated

Can you link to the PR where you did the translation?

**Comment by BILLYBELT** [comment]
1 parent 0f6d2a3
<https://github.com/nash-io/locale/commit/0f6d2a38cb9c47fff447f4ff3674744cc5a7a2c8>
 commit 138440aa8f11b60448bd2d80b258838ec49393dc
https://github.com/nash-io/locale/commit/138440aa8f11b60448bd2d80b258838ec49393dc#diff-2b5990380aac51854aa963d75d28e617


Le mar. 23 juin 2020 à 13:21, Chris Fenwick <notifications@github.com> a
écrit :

**Comment by lexipenia** [comment]
@BILLYBELT I'm putting them back in here:
https://github.com/nash-io/locale/pull/455

Looks like something went wrong when merging various PRs this morning.

**Pull request merged**
