### PR TITLE
Update nl_NL_601_1100

### PR DESCRIPTION
**Pull request by NichaT**

### CODE REVIEW

**Comment by NichaT** [comment]
Big update, I will do a double check. I will ping @lexipenia when it's ready.

**Comment by NichaT** [comment]
@lexipenia I'll try to keep it shorter next time. My double check is complete. I do have two small comments I want to pass by you.

At line 612/614 the document talks about 'Secret word backup'. While translating the lines around 612/614 the document speaks of 'secret words'. For me it would feel more natural if it was 'Secret words backup'.

The second comment is about line 653 it says:

"Enter the verification code generated by your authenticator app".

The next line on the "input-placeholder" talks about "Authentication code". I would think this should be "Verification code" as well.

You have more information about the context, so it thought I would run it by you just to be sure.

**Comment by NichaT** [comment]
I'll ask in the telegram group for a review.

**Comment by lexipenia** [comment]
@NichaT 
> At line 612/614 the document talks about 'Secret word backup'. While translating the lines around 612/614 the document speaks of 'secret words'. For me it would feel more natural if it was 'Secret words backup'.

I'm afraid that's just not how you'd say it in English.

> The second comment is about line 653 it says:
> "Enter the verification code generated by your authenticator app".
> 
> The next line on the "input-placeholder" talks about "Authentication code". I would think this should be "Verification code" as well.

Yes, we should make the placeholder match. I will edit it.

**Comment by NichaT** [comment]
@lexipenia got it! I kept the translation also as singular just like the English translation. Though in Dutch it would maybe feel more natural if it was plural. Maybe someone 'Dutch' reviewing this document can have a look.

I looked at the German translation for inspiration, I notice in this file the word 'backup' is completely left out (Note: I hardly speak any German). In this context I don't know the value of the word backup.

**Comment by lexipenia** [comment]
German isn't complete yet. So it may change. Perhaps they think it's better without the word?

btw, I am not changing "Authentication code" since it is the standard placeholder for all 2FA fields. Instead, I'm removing the superfluous word `verification` from the first line, so it just says `enter the code`.

The files here should be updated with the changes soon, once we get our system in place for managing the translations.

**Comment by lexipenia** [comment]
@NichaT I'm merging this in now. You can continue reviewing / correcting these lines later.

**Pull request merged**
