### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by NichaT**
"Resent" should be "Resend"

### CODE REVIEW

**Comment by lexipenia** [comment]
@NichaT Please do not update the `en.json` file. Just notify Nash / me if you believe you have found a typo within the UI, where you have full context. In this case, this is the status that appears on the `Retry` button once the code has already been sent a second time.

**Comment by lexipenia** [comment]
The change in line 559 is also incorrect. `Sent` is the past participle of `Send` and is what is required here for these statuses.

**Comment by NichaT** [comment]
@lexipenia got it. Next time I will contact you directly if I think I found a typo.

**Comment by lexipenia** [comment]
@NichaT Thanks. We check things thoroughly but sometimes a mistake makes it through. It's important to be aware of the context as well – for example, regarding the button status above.

**Comment by NichaT** [comment]
@lexipenia that's definitely something I'm also encountering when translating to Dutch. I'm guessing there should be enough work after implementation (:

**Comment by lexipenia** [comment]
@NichaT Please ask me if you're not sure about context. That's what I'm here for! It's better to clarify than to guess, and I am very familiar with the original copy file.

**Pull request closed without merging**
