### PR TITLE
Create nl_NL

### PR DESCRIPTION
**Pull request by prik**
Because you can't expect all Dutchies to understand English. Maybe the crypto audience can, but definitely not the entire country. If we want to provide the best UX, providing as much languages as possible is part of that.

### CODE REVIEW

**Comment by canesin** [comment]
Alright, the Nash Dutchies knows better the Dutchies :cheese:

**Comment by canesin** [comment]
@prik could you add extension .json to the file and add the link/info to the README.md ?

**Comment by canesin** [comment]
No need @prik I did it on my upload of our WIP German translation.

**Comment by prik** [comment]
Awesome @canesin 🥂

**Pull request closed without merging**
