### PR TITLE
Update nl_NL.json

### PR DESCRIPTION
**Pull request by GLS9000**
Hi I  rechecked and translated the strings I did this morning. Seems like I had to redo some translating though

### CODE REVIEW

**Comment by lexipenia** [comment]
> Hi I rechecked and translated the strings I did this morning. Seems like I had to redo some translating though

You didn't have to repeat things -- the problem is that you started working on `master`, not on the "New translation strings" branch, where you already did your translations.

I haven't merged your existing translations into master yet, so they aren't there. You should be working on this version of the file, in the special branch, not the version in `master`:
https://github.com/nash-io/locale/blob/nl_NL.json-2020-07-11-15-50-42/locales/nl_NL.json

Sorry if this wasn't clear. Are you able to check the version of the file listed above and make changes to that? I can close this PR.

**Comment by lexipenia** [comment]
We're working on making this process as easy as possible. I'd hoped just sending out the link with the file to work on would be OK. I will have to remember to do that if there are things left out.

**Comment by GLS9000** [comment]
> 
> 
> > Hi I rechecked and translated the strings I did this morning. Seems like I had to redo some translating though
> 
> You didn't have to repeat things -- the problem is that you started working on `master`, not on the "New translation strings" branch, where you already did your translations.
> 
> I haven't merged your existing translations into master yet, so they aren't there. You should be working on this version of the file, in the special branch, not the version in `master`:
> https://github.com/nash-io/locale/blob/nl_NL.json-2020-07-11-15-50-42/locales/nl_NL.json
> 
> Sorry if this wasn't clear. Are you able to check the version of the file listed above and make changes to that? I can close this PR.

No problem! Should I from now on always use the link above?

**Comment by lexipenia** [comment]
> No problem! Should I from now on always use the link above?

It looks like they are all done apart from one (which is in an untranslated block anyway). So I will just merge it all.

**Pull request closed without merging**
