### PR TITLE
Lines 3000-3200.

### PR DESCRIPTION
**Pull request by Marcpepe**
Heads up: I changed the en.json file on 2 lines, because it looked like the wording was outdated. It would be best if you confirm first :)

### CODE REVIEW

**Comment by Marcpepe** [comment]
@lexipenia Did you see my above comment?

**Comment by lexipenia** [comment]
> @lexipenia Did you see my above comment?

No, I didn't. The repo isn't meant for editing the English file, which is treated differently anyway (so I don't think this change will get included). If you believe something in the English file is incorrect, best ping me separately with the issue.

**Comment by Marcpepe** [comment]
@lexipenia Ah ok, because I made a few changes also in other commits. Let's see.. Here are the commits where I made changes in the en.json file (all of them):

- https://github.com/nash-io/locale/commit/0fa8f76c71a6dc22e7fc97d502bf3253168717c7
- https://github.com/nash-io/locale/commit/09689431d41f16d6d371a444291c341d8550ad7e
- https://github.com/nash-io/locale/commit/9b3c6758a30cb91865bb5ea0da72c27470536a49
- https://github.com/nash-io/locale/commit/03db8b920faea4124d85ba045492406632c307d0

It's mostly typos and tiny errors.

**Comment by lexipenia** [comment]
@Marcpepe You'd best @-mention me, otherwise I probably won't see these things.

**Pull request merged**
